services:
  random-words-api:
    container_name: random-words-api
    # The following is for development
    image: maven:3.9-eclipse-temurin-21
    working_dir: /app
    volumes: 
      - .:/app
    command: mvn spring-boot:run
    # Until here. Will be changed once done
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://random-words-db:5432/random_words_generator
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - random-words-db

  random-words-db:
    container_name: random-words-db
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: random_words_generator
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}